export const fighters_frames = {
  warrior: {
    idle: 10,
    run: 6,
    jump: 2,
    fall: 2,
    attack_basic: 4,
    attack_special: 5,
    hit: 3,
    death: 9,
    offset: {
      '-1': { x: 145, y: 120 },
      1: { x: 195, y: 120 },
    },
    framesMax: 10,
    name: 'warrior',
    scale: 2.5,
    src: '../assets/fighters/warrior/idle.png',
  },
  rogue: {
    idle: 8,
    run: 8,
    jump: 2,
    fall: 2,
    attack_basic: 4,
    attack_special: 4,
    hit: 4,
    death: 6,
    offset: {
      '-1': { x: 150, y: 127 },
      1: { x: 200, y: 127 },
    },
    framesMax: 8,
    name: 'rogue',
    scale: 2.35,
    src: '../assets/fighters/rogue/idle.png',
  },
  ninja: {
    idle: 8,
    run: 8,
    jump: 2,
    fall: 2,
    attack_basic: 4,
    attack_special: 4,
    hit: 3,
    death: 7,
    offset: {
      '-1': { x: 170, y: 145 },
      1: { x: 220, y: 145 },
    },
    framesMax: 8,
    name: 'ninja',
    scale: 1.9,
    src: '../assets/fighters/ninja/idle.png',
  },
  samurai: {
    idle: 8,
    run: 8,
    jump: 2,
    fall: 2,
    attack_basic: 4,
    attack_special: 4,
    hit: 4,
    death: 6,
    offset: {
      '-1': { x: 190, y: 165 },
      1: { x: 240, y: 165 },
    },
    framesMax: 8,
    name: 'samurai',
    scale: 2.15,
    src: '../assets/fighters/samurai/idle.png',
  },
  nightborne: {
    idle: 9,
    run: 6,
    jump: 9,
    fall: 9,
    attack_basic: 12,
    attack_special: 12,
    hit: 5,
    death: 23,
    offset: {
      '-1': { x: 135, y: 120 },
      1: { x: 185, y: 120 },
    },
    framesMax: 9,
    name: 'nightborne',
    scale: 1.15,
    src: '../assets/fighters/nightborne/idle.png',
  },
};
